{
  "formatVersion": "1.1",
  "component": {
    "group": "com.company",
    "module": "app",
    "version": "6.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "debugRuntime",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.native.optimized": false,
        "org.gradle.usage": "native-runtime"
      },
      "available-at": {
        "url": "../../app_debug/6.5.4/app_debug-6.5.4.module",
        "group": "com.company",
        "module": "app_debug",
        "version": "6.5.4"
      }
    },
    {
      "name": "releaseRuntime",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.native.optimized": true,
        "org.gradle.usage": "native-runtime"
      },
      "available-at": {
        "url": "../../app_release/6.5.4/app_release-6.5.4.module",
        "group": "com.company",
        "module": "app_release",
        "version": "6.5.4"
      }
    }
  ]
}
